### ISSUE TITLE
Profile the ice40_import_routing_from_icebox script and make it fast

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-arch-defs#192] opened 2018-07-14 16:52 UTC
The current [`ice40_import_routing_from_icebox.py`](ice40/utils/ice40_import_routing_from_icebox.py) takes a long time to run. Currently the script is written to make it easy to understand and debug the rr_graph. There is plenty of room for optimization and making it fast!

Someone should profile it and make it fast!

**Comment by elmsfu** [comment] 2019-03-26 21:21
Duplicate of #196

**Closed by elmsfu** 2019-03-26 21:21 UTC
Labels: arch-ice40, help wanted, lang-python, lang-xml, type-utils
